// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: api/proto/snake/v1/snake.proto

package snake

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SnakeGameService_JoinGame_FullMethodName      = "/api.proto.snake.v1.SnakeGameService/JoinGame"
	SnakeGameService_SendDirection_FullMethodName = "/api.proto.snake.v1.SnakeGameService/SendDirection"
	SnakeGameService_GetTopPlayers_FullMethodName = "/api.proto.snake.v1.SnakeGameService/GetTopPlayers"
)

// SnakeGameServiceClient is the client API for SnakeGameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SnakeGameServiceClient interface {
	JoinGame(ctx context.Context, in *JoinGameRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JoinGameResponse], error)
	SendDirection(ctx context.Context, in *SendDirectionRequest, opts ...grpc.CallOption) (*SendDirectionResponse, error)
	GetTopPlayers(ctx context.Context, in *GetTopPlayersRequest, opts ...grpc.CallOption) (*GetTopPlayersResponse, error)
}

type snakeGameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSnakeGameServiceClient(cc grpc.ClientConnInterface) SnakeGameServiceClient {
	return &snakeGameServiceClient{cc}
}

func (c *snakeGameServiceClient) JoinGame(ctx context.Context, in *JoinGameRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JoinGameResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SnakeGameService_ServiceDesc.Streams[0], SnakeGameService_JoinGame_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[JoinGameRequest, JoinGameResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SnakeGameService_JoinGameClient = grpc.ServerStreamingClient[JoinGameResponse]

func (c *snakeGameServiceClient) SendDirection(ctx context.Context, in *SendDirectionRequest, opts ...grpc.CallOption) (*SendDirectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendDirectionResponse)
	err := c.cc.Invoke(ctx, SnakeGameService_SendDirection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snakeGameServiceClient) GetTopPlayers(ctx context.Context, in *GetTopPlayersRequest, opts ...grpc.CallOption) (*GetTopPlayersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopPlayersResponse)
	err := c.cc.Invoke(ctx, SnakeGameService_GetTopPlayers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnakeGameServiceServer is the server API for SnakeGameService service.
// All implementations must embed UnimplementedSnakeGameServiceServer
// for forward compatibility.
type SnakeGameServiceServer interface {
	JoinGame(*JoinGameRequest, grpc.ServerStreamingServer[JoinGameResponse]) error
	SendDirection(context.Context, *SendDirectionRequest) (*SendDirectionResponse, error)
	GetTopPlayers(context.Context, *GetTopPlayersRequest) (*GetTopPlayersResponse, error)
	mustEmbedUnimplementedSnakeGameServiceServer()
}

// UnimplementedSnakeGameServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSnakeGameServiceServer struct{}

func (UnimplementedSnakeGameServiceServer) JoinGame(*JoinGameRequest, grpc.ServerStreamingServer[JoinGameResponse]) error {
	return status.Error(codes.Unimplemented, "method JoinGame not implemented")
}
func (UnimplementedSnakeGameServiceServer) SendDirection(context.Context, *SendDirectionRequest) (*SendDirectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendDirection not implemented")
}
func (UnimplementedSnakeGameServiceServer) GetTopPlayers(context.Context, *GetTopPlayersRequest) (*GetTopPlayersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopPlayers not implemented")
}
func (UnimplementedSnakeGameServiceServer) mustEmbedUnimplementedSnakeGameServiceServer() {}
func (UnimplementedSnakeGameServiceServer) testEmbeddedByValue()                          {}

// UnsafeSnakeGameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnakeGameServiceServer will
// result in compilation errors.
type UnsafeSnakeGameServiceServer interface {
	mustEmbedUnimplementedSnakeGameServiceServer()
}

func RegisterSnakeGameServiceServer(s grpc.ServiceRegistrar, srv SnakeGameServiceServer) {
	// If the following call panics, it indicates UnimplementedSnakeGameServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SnakeGameService_ServiceDesc, srv)
}

func _SnakeGameService_JoinGame_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JoinGameRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SnakeGameServiceServer).JoinGame(m, &grpc.GenericServerStream[JoinGameRequest, JoinGameResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SnakeGameService_JoinGameServer = grpc.ServerStreamingServer[JoinGameResponse]

func _SnakeGameService_SendDirection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendDirectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnakeGameServiceServer).SendDirection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnakeGameService_SendDirection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnakeGameServiceServer).SendDirection(ctx, req.(*SendDirectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnakeGameService_GetTopPlayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopPlayersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnakeGameServiceServer).GetTopPlayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnakeGameService_GetTopPlayers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnakeGameServiceServer).GetTopPlayers(ctx, req.(*GetTopPlayersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SnakeGameService_ServiceDesc is the grpc.ServiceDesc for SnakeGameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SnakeGameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.proto.snake.v1.SnakeGameService",
	HandlerType: (*SnakeGameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendDirection",
			Handler:    _SnakeGameService_SendDirection_Handler,
		},
		{
			MethodName: "GetTopPlayers",
			Handler:    _SnakeGameService_GetTopPlayers_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "JoinGame",
			Handler:       _SnakeGameService_JoinGame_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/snake/v1/snake.proto",
}
