// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/snake/v1/snake.proto

package snake

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Direction int32

const (
	Direction_DIRECTION_UNSPECIFIED Direction = 0
	Direction_DIRECTION_UP          Direction = 1
	Direction_DIRECTION_DOWN        Direction = 2
	Direction_DIRECTION_LEFT        Direction = 3
	Direction_DIRECTION_RIGHT       Direction = 4
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "DIRECTION_UNSPECIFIED",
		1: "DIRECTION_UP",
		2: "DIRECTION_DOWN",
		3: "DIRECTION_LEFT",
		4: "DIRECTION_RIGHT",
	}
	Direction_value = map[string]int32{
		"DIRECTION_UNSPECIFIED": 0,
		"DIRECTION_UP":          1,
		"DIRECTION_DOWN":        2,
		"DIRECTION_LEFT":        3,
		"DIRECTION_RIGHT":       4,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_snake_v1_snake_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_api_proto_snake_v1_snake_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_snake_v1_snake_proto_rawDescGZIP(), []int{0}
}

type GetTopPlayersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopPlayers    []*PlayerScore         `protobuf:"bytes,1,rep,name=top_players,json=topPlayers,proto3" json:"top_players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopPlayersResponse) Reset() {
	*x = GetTopPlayersResponse{}
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopPlayersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopPlayersResponse) ProtoMessage() {}

func (x *GetTopPlayersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopPlayersResponse.ProtoReflect.Descriptor instead.
func (*GetTopPlayersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_snake_v1_snake_proto_rawDescGZIP(), []int{0}
}

func (x *GetTopPlayersResponse) GetTopPlayers() []*PlayerScore {
	if x != nil {
		return x.TopPlayers
	}
	return nil
}

type PlayerScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerName    string                 `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerScore) Reset() {
	*x = PlayerScore{}
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerScore) ProtoMessage() {}

func (x *PlayerScore) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerScore.ProtoReflect.Descriptor instead.
func (*PlayerScore) Descriptor() ([]byte, []int) {
	return file_api_proto_snake_v1_snake_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerScore) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *PlayerScore) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type JoinGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerName    string                 `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGameRequest) Reset() {
	*x = JoinGameRequest{}
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameRequest) ProtoMessage() {}

func (x *JoinGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameRequest.ProtoReflect.Descriptor instead.
func (*JoinGameRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_snake_v1_snake_proto_rawDescGZIP(), []int{2}
}

func (x *JoinGameRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

type JoinGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*Player              `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	Food          []*Point               `protobuf:"bytes,2,rep,name=food,proto3" json:"food,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGameResponse) Reset() {
	*x = JoinGameResponse{}
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameResponse) ProtoMessage() {}

func (x *JoinGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameResponse.ProtoReflect.Descriptor instead.
func (*JoinGameResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_snake_v1_snake_proto_rawDescGZIP(), []int{3}
}

func (x *JoinGameResponse) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *JoinGameResponse) GetFood() []*Point {
	if x != nil {
		return x.Food
	}
	return nil
}

type SendDirectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerName    string                 `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	Direction     Direction              `protobuf:"varint,2,opt,name=direction,proto3,enum=api.proto.snake.v1.Direction" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendDirectionRequest) Reset() {
	*x = SendDirectionRequest{}
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendDirectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDirectionRequest) ProtoMessage() {}

func (x *SendDirectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDirectionRequest.ProtoReflect.Descriptor instead.
func (*SendDirectionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_snake_v1_snake_proto_rawDescGZIP(), []int{4}
}

func (x *SendDirectionRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *SendDirectionRequest) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNSPECIFIED
}

type SendDirectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendDirectionResponse) Reset() {
	*x = SendDirectionResponse{}
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendDirectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDirectionResponse) ProtoMessage() {}

func (x *SendDirectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDirectionResponse.ProtoReflect.Descriptor instead.
func (*SendDirectionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_snake_v1_snake_proto_rawDescGZIP(), []int{5}
}

type GetTopPlayersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopPlayersRequest) Reset() {
	*x = GetTopPlayersRequest{}
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopPlayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopPlayersRequest) ProtoMessage() {}

func (x *GetTopPlayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopPlayersRequest.ProtoReflect.Descriptor instead.
func (*GetTopPlayersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_snake_v1_snake_proto_rawDescGZIP(), []int{6}
}

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Body          []*Point               `protobuf:"bytes,2,rep,name=body,proto3" json:"body,omitempty"`
	Alive         bool                   `protobuf:"varint,3,opt,name=alive,proto3" json:"alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_api_proto_snake_v1_snake_proto_rawDescGZIP(), []int{7}
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetBody() []*Point {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Player) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_api_proto_snake_v1_snake_proto_rawDescGZIP(), []int{8}
}

func (x *Point) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_api_proto_snake_v1_snake_proto protoreflect.FileDescriptor

const file_api_proto_snake_v1_snake_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/snake/v1/snake.proto\x12\x12api.proto.snake.v1\"Y\n" +
	"\x15GetTopPlayersResponse\x12@\n" +
	"\vtop_players\x18\x01 \x03(\v2\x1f.api.proto.snake.v1.PlayerScoreR\n" +
	"topPlayers\"D\n" +
	"\vPlayerScore\x12\x1f\n" +
	"\vplayer_name\x18\x01 \x01(\tR\n" +
	"playerName\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\"2\n" +
	"\x0fJoinGameRequest\x12\x1f\n" +
	"\vplayer_name\x18\x01 \x01(\tR\n" +
	"playerName\"w\n" +
	"\x10JoinGameResponse\x124\n" +
	"\aplayers\x18\x01 \x03(\v2\x1a.api.proto.snake.v1.PlayerR\aplayers\x12-\n" +
	"\x04food\x18\x02 \x03(\v2\x19.api.proto.snake.v1.PointR\x04food\"t\n" +
	"\x14SendDirectionRequest\x12\x1f\n" +
	"\vplayer_name\x18\x01 \x01(\tR\n" +
	"playerName\x12;\n" +
	"\tdirection\x18\x02 \x01(\x0e2\x1d.api.proto.snake.v1.DirectionR\tdirection\"\x17\n" +
	"\x15SendDirectionResponse\"\x16\n" +
	"\x14GetTopPlayersRequest\"a\n" +
	"\x06Player\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12-\n" +
	"\x04body\x18\x02 \x03(\v2\x19.api.proto.snake.v1.PointR\x04body\x12\x14\n" +
	"\x05alive\x18\x03 \x01(\bR\x05alive\"#\n" +
	"\x05Point\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y*u\n" +
	"\tDirection\x12\x19\n" +
	"\x15DIRECTION_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fDIRECTION_UP\x10\x01\x12\x12\n" +
	"\x0eDIRECTION_DOWN\x10\x02\x12\x12\n" +
	"\x0eDIRECTION_LEFT\x10\x03\x12\x13\n" +
	"\x0fDIRECTION_RIGHT\x10\x042\xb7\x02\n" +
	"\x10SnakeGameService\x12W\n" +
	"\bJoinGame\x12#.api.proto.snake.v1.JoinGameRequest\x1a$.api.proto.snake.v1.JoinGameResponse0\x01\x12d\n" +
	"\rSendDirection\x12(.api.proto.snake.v1.SendDirectionRequest\x1a).api.proto.snake.v1.SendDirectionResponse\x12d\n" +
	"\rGetTopPlayers\x12(.api.proto.snake.v1.GetTopPlayersRequest\x1a).api.proto.snake.v1.GetTopPlayersResponseB&Z$GoSnakeGame/api/proto/snake/v1;snakeb\x06proto3"

var (
	file_api_proto_snake_v1_snake_proto_rawDescOnce sync.Once
	file_api_proto_snake_v1_snake_proto_rawDescData []byte
)

func file_api_proto_snake_v1_snake_proto_rawDescGZIP() []byte {
	file_api_proto_snake_v1_snake_proto_rawDescOnce.Do(func() {
		file_api_proto_snake_v1_snake_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_snake_v1_snake_proto_rawDesc), len(file_api_proto_snake_v1_snake_proto_rawDesc)))
	})
	return file_api_proto_snake_v1_snake_proto_rawDescData
}

var file_api_proto_snake_v1_snake_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_snake_v1_snake_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_proto_snake_v1_snake_proto_goTypes = []any{
	(Direction)(0),                // 0: api.proto.snake.v1.Direction
	(*GetTopPlayersResponse)(nil), // 1: api.proto.snake.v1.GetTopPlayersResponse
	(*PlayerScore)(nil),           // 2: api.proto.snake.v1.PlayerScore
	(*JoinGameRequest)(nil),       // 3: api.proto.snake.v1.JoinGameRequest
	(*JoinGameResponse)(nil),      // 4: api.proto.snake.v1.JoinGameResponse
	(*SendDirectionRequest)(nil),  // 5: api.proto.snake.v1.SendDirectionRequest
	(*SendDirectionResponse)(nil), // 6: api.proto.snake.v1.SendDirectionResponse
	(*GetTopPlayersRequest)(nil),  // 7: api.proto.snake.v1.GetTopPlayersRequest
	(*Player)(nil),                // 8: api.proto.snake.v1.Player
	(*Point)(nil),                 // 9: api.proto.snake.v1.Point
}
var file_api_proto_snake_v1_snake_proto_depIdxs = []int32{
	2, // 0: api.proto.snake.v1.GetTopPlayersResponse.top_players:type_name -> api.proto.snake.v1.PlayerScore
	8, // 1: api.proto.snake.v1.JoinGameResponse.players:type_name -> api.proto.snake.v1.Player
	9, // 2: api.proto.snake.v1.JoinGameResponse.food:type_name -> api.proto.snake.v1.Point
	0, // 3: api.proto.snake.v1.SendDirectionRequest.direction:type_name -> api.proto.snake.v1.Direction
	9, // 4: api.proto.snake.v1.Player.body:type_name -> api.proto.snake.v1.Point
	3, // 5: api.proto.snake.v1.SnakeGameService.JoinGame:input_type -> api.proto.snake.v1.JoinGameRequest
	5, // 6: api.proto.snake.v1.SnakeGameService.SendDirection:input_type -> api.proto.snake.v1.SendDirectionRequest
	7, // 7: api.proto.snake.v1.SnakeGameService.GetTopPlayers:input_type -> api.proto.snake.v1.GetTopPlayersRequest
	4, // 8: api.proto.snake.v1.SnakeGameService.JoinGame:output_type -> api.proto.snake.v1.JoinGameResponse
	6, // 9: api.proto.snake.v1.SnakeGameService.SendDirection:output_type -> api.proto.snake.v1.SendDirectionResponse
	1, // 10: api.proto.snake.v1.SnakeGameService.GetTopPlayers:output_type -> api.proto.snake.v1.GetTopPlayersResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_snake_v1_snake_proto_init() }
func file_api_proto_snake_v1_snake_proto_init() {
	if File_api_proto_snake_v1_snake_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_snake_v1_snake_proto_rawDesc), len(file_api_proto_snake_v1_snake_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_snake_v1_snake_proto_goTypes,
		DependencyIndexes: file_api_proto_snake_v1_snake_proto_depIdxs,
		EnumInfos:         file_api_proto_snake_v1_snake_proto_enumTypes,
		MessageInfos:      file_api_proto_snake_v1_snake_proto_msgTypes,
	}.Build()
	File_api_proto_snake_v1_snake_proto = out.File
	file_api_proto_snake_v1_snake_proto_goTypes = nil
	file_api_proto_snake_v1_snake_proto_depIdxs = nil
}
