// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/snake/v1/snake.proto

package snake

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameMode int32

const (
	GameMode_MODE_UNSPECIFIED GameMode = 0
	GameMode_MODE_SOLO        GameMode = 1
	GameMode_MODE_1V1         GameMode = 2
	GameMode_MODE_FFA         GameMode = 3 // 1v1v1v1
)

// Enum value maps for GameMode.
var (
	GameMode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "MODE_SOLO",
		2: "MODE_1V1",
		3: "MODE_FFA",
	}
	GameMode_value = map[string]int32{
		"MODE_UNSPECIFIED": 0,
		"MODE_SOLO":        1,
		"MODE_1V1":         2,
		"MODE_FFA":         3,
	}
)

func (x GameMode) Enum() *GameMode {
	p := new(GameMode)
	*p = x
	return p
}

func (x GameMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameMode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_snake_v1_snake_proto_enumTypes[0].Descriptor()
}

func (GameMode) Type() protoreflect.EnumType {
	return &file_api_proto_snake_v1_snake_proto_enumTypes[0]
}

func (x GameMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameMode.Descriptor instead.
func (GameMode) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_snake_v1_snake_proto_rawDescGZIP(), []int{0}
}

type Direction int32

const (
	Direction_DIRECTION_UNSPECIFIED Direction = 0
	Direction_DIRECTION_UP          Direction = 1
	Direction_DIRECTION_DOWN        Direction = 2
	Direction_DIRECTION_LEFT        Direction = 3
	Direction_DIRECTION_RIGHT       Direction = 4
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "DIRECTION_UNSPECIFIED",
		1: "DIRECTION_UP",
		2: "DIRECTION_DOWN",
		3: "DIRECTION_LEFT",
		4: "DIRECTION_RIGHT",
	}
	Direction_value = map[string]int32{
		"DIRECTION_UNSPECIFIED": 0,
		"DIRECTION_UP":          1,
		"DIRECTION_DOWN":        2,
		"DIRECTION_LEFT":        3,
		"DIRECTION_RIGHT":       4,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_snake_v1_snake_proto_enumTypes[1].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_api_proto_snake_v1_snake_proto_enumTypes[1]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_snake_v1_snake_proto_rawDescGZIP(), []int{1}
}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMessage_Join
	//	*ClientMessage_Direction
	//	*ClientMessage_Top
	//	*ClientMessage_CreateRoom
	Payload       isClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_snake_v1_snake_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetPayload() isClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMessage) GetJoin() *JoinGameRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Join); ok {
			return x.Join
		}
	}
	return nil
}

func (x *ClientMessage) GetDirection() *SendDirectionRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Direction); ok {
			return x.Direction
		}
	}
	return nil
}

func (x *ClientMessage) GetTop() *GetTopPlayersRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Top); ok {
			return x.Top
		}
	}
	return nil
}

func (x *ClientMessage) GetCreateRoom() *CreateRoomRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_CreateRoom); ok {
			return x.CreateRoom
		}
	}
	return nil
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_Join struct {
	Join *JoinGameRequest `protobuf:"bytes,1,opt,name=join,proto3,oneof"`
}

type ClientMessage_Direction struct {
	Direction *SendDirectionRequest `protobuf:"bytes,2,opt,name=direction,proto3,oneof"`
}

type ClientMessage_Top struct {
	Top *GetTopPlayersRequest `protobuf:"bytes,3,opt,name=top,proto3,oneof"`
}

type ClientMessage_CreateRoom struct {
	CreateRoom *CreateRoomRequest `protobuf:"bytes,4,opt,name=create_room,json=createRoom,proto3,oneof"`
}

func (*ClientMessage_Join) isClientMessage_Payload() {}

func (*ClientMessage_Direction) isClientMessage_Payload() {}

func (*ClientMessage_Top) isClientMessage_Payload() {}

func (*ClientMessage_CreateRoom) isClientMessage_Payload() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Update
	//	*ServerMessage_Top
	//	*ServerMessage_RoomCreated
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_snake_v1_snake_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetUpdate() *JoinGameResponse {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Update); ok {
			return x.Update
		}
	}
	return nil
}

func (x *ServerMessage) GetTop() *GetTopPlayersResponse {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Top); ok {
			return x.Top
		}
	}
	return nil
}

func (x *ServerMessage) GetRoomCreated() *CreateRoomResponse {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_RoomCreated); ok {
			return x.RoomCreated
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Update struct {
	Update *JoinGameResponse `protobuf:"bytes,1,opt,name=update,proto3,oneof"`
}

type ServerMessage_Top struct {
	Top *GetTopPlayersResponse `protobuf:"bytes,2,opt,name=top,proto3,oneof"`
}

type ServerMessage_RoomCreated struct {
	RoomCreated *CreateRoomResponse `protobuf:"bytes,3,opt,name=room_created,json=roomCreated,proto3,oneof"`
}

func (*ServerMessage_Update) isServerMessage_Payload() {}

func (*ServerMessage_Top) isServerMessage_Payload() {}

func (*ServerMessage_RoomCreated) isServerMessage_Payload() {}

type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerName    string                 `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	Mode          GameMode               `protobuf:"varint,2,opt,name=mode,proto3,enum=api.proto.snake.v1.GameMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_snake_v1_snake_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRoomRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *CreateRoomRequest) GetMode() GameMode {
	if x != nil {
		return x.Mode
	}
	return GameMode_MODE_UNSPECIFIED
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	InviteLink    string                 `protobuf:"bytes,2,opt,name=invite_link,json=inviteLink,proto3" json:"invite_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_snake_v1_snake_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoomResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CreateRoomResponse) GetInviteLink() string {
	if x != nil {
		return x.InviteLink
	}
	return ""
}

type GetTopPlayersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopPlayers    []*PlayerScore         `protobuf:"bytes,1,rep,name=top_players,json=topPlayers,proto3" json:"top_players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopPlayersResponse) Reset() {
	*x = GetTopPlayersResponse{}
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopPlayersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopPlayersResponse) ProtoMessage() {}

func (x *GetTopPlayersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopPlayersResponse.ProtoReflect.Descriptor instead.
func (*GetTopPlayersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_snake_v1_snake_proto_rawDescGZIP(), []int{4}
}

func (x *GetTopPlayersResponse) GetTopPlayers() []*PlayerScore {
	if x != nil {
		return x.TopPlayers
	}
	return nil
}

type PlayerScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerName    string                 `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerScore) Reset() {
	*x = PlayerScore{}
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerScore) ProtoMessage() {}

func (x *PlayerScore) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerScore.ProtoReflect.Descriptor instead.
func (*PlayerScore) Descriptor() ([]byte, []int) {
	return file_api_proto_snake_v1_snake_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerScore) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *PlayerScore) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type JoinGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerName    string                 `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGameRequest) Reset() {
	*x = JoinGameRequest{}
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameRequest) ProtoMessage() {}

func (x *JoinGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameRequest.ProtoReflect.Descriptor instead.
func (*JoinGameRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_snake_v1_snake_proto_rawDescGZIP(), []int{6}
}

func (x *JoinGameRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *JoinGameRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type JoinGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*Player              `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	Food          []*Point               `protobuf:"bytes,2,rep,name=food,proto3" json:"food,omitempty"`
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Mode          GameMode               `protobuf:"varint,4,opt,name=mode,proto3,enum=api.proto.snake.v1.GameMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGameResponse) Reset() {
	*x = JoinGameResponse{}
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameResponse) ProtoMessage() {}

func (x *JoinGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameResponse.ProtoReflect.Descriptor instead.
func (*JoinGameResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_snake_v1_snake_proto_rawDescGZIP(), []int{7}
}

func (x *JoinGameResponse) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *JoinGameResponse) GetFood() []*Point {
	if x != nil {
		return x.Food
	}
	return nil
}

func (x *JoinGameResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *JoinGameResponse) GetMode() GameMode {
	if x != nil {
		return x.Mode
	}
	return GameMode_MODE_UNSPECIFIED
}

type SendDirectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerName    string                 `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Direction     Direction              `protobuf:"varint,3,opt,name=direction,proto3,enum=api.proto.snake.v1.Direction" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendDirectionRequest) Reset() {
	*x = SendDirectionRequest{}
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendDirectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDirectionRequest) ProtoMessage() {}

func (x *SendDirectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDirectionRequest.ProtoReflect.Descriptor instead.
func (*SendDirectionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_snake_v1_snake_proto_rawDescGZIP(), []int{8}
}

func (x *SendDirectionRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *SendDirectionRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SendDirectionRequest) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNSPECIFIED
}

type SendDirectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendDirectionResponse) Reset() {
	*x = SendDirectionResponse{}
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendDirectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDirectionResponse) ProtoMessage() {}

func (x *SendDirectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDirectionResponse.ProtoReflect.Descriptor instead.
func (*SendDirectionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_snake_v1_snake_proto_rawDescGZIP(), []int{9}
}

type GetTopPlayersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopPlayersRequest) Reset() {
	*x = GetTopPlayersRequest{}
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopPlayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopPlayersRequest) ProtoMessage() {}

func (x *GetTopPlayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopPlayersRequest.ProtoReflect.Descriptor instead.
func (*GetTopPlayersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_snake_v1_snake_proto_rawDescGZIP(), []int{10}
}

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Body          []*Point               `protobuf:"bytes,2,rep,name=body,proto3" json:"body,omitempty"`
	Alive         bool                   `protobuf:"varint,3,opt,name=alive,proto3" json:"alive,omitempty"`
	Id            int32                  `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	Direction     Direction              `protobuf:"varint,5,opt,name=direction,proto3,enum=api.proto.snake.v1.Direction" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_api_proto_snake_v1_snake_proto_rawDescGZIP(), []int{11}
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetBody() []*Point {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Player) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *Player) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Player) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNSPECIFIED
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_snake_v1_snake_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_api_proto_snake_v1_snake_proto_rawDescGZIP(), []int{12}
}

func (x *Point) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_api_proto_snake_v1_snake_proto protoreflect.FileDescriptor

const file_api_proto_snake_v1_snake_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/snake/v1/snake.proto\x12\x12api.proto.snake.v1\"\xa7\x02\n" +
	"\rClientMessage\x129\n" +
	"\x04join\x18\x01 \x01(\v2#.api.proto.snake.v1.JoinGameRequestH\x00R\x04join\x12H\n" +
	"\tdirection\x18\x02 \x01(\v2(.api.proto.snake.v1.SendDirectionRequestH\x00R\tdirection\x12<\n" +
	"\x03top\x18\x03 \x01(\v2(.api.proto.snake.v1.GetTopPlayersRequestH\x00R\x03top\x12H\n" +
	"\vcreate_room\x18\x04 \x01(\v2%.api.proto.snake.v1.CreateRoomRequestH\x00R\n" +
	"createRoomB\t\n" +
	"\apayload\"\xe6\x01\n" +
	"\rServerMessage\x12>\n" +
	"\x06update\x18\x01 \x01(\v2$.api.proto.snake.v1.JoinGameResponseH\x00R\x06update\x12=\n" +
	"\x03top\x18\x02 \x01(\v2).api.proto.snake.v1.GetTopPlayersResponseH\x00R\x03top\x12K\n" +
	"\froom_created\x18\x03 \x01(\v2&.api.proto.snake.v1.CreateRoomResponseH\x00R\vroomCreatedB\t\n" +
	"\apayload\"f\n" +
	"\x11CreateRoomRequest\x12\x1f\n" +
	"\vplayer_name\x18\x01 \x01(\tR\n" +
	"playerName\x120\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x1c.api.proto.snake.v1.GameModeR\x04mode\"N\n" +
	"\x12CreateRoomResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vinvite_link\x18\x02 \x01(\tR\n" +
	"inviteLink\"Y\n" +
	"\x15GetTopPlayersResponse\x12@\n" +
	"\vtop_players\x18\x01 \x03(\v2\x1f.api.proto.snake.v1.PlayerScoreR\n" +
	"topPlayers\"D\n" +
	"\vPlayerScore\x12\x1f\n" +
	"\vplayer_name\x18\x01 \x01(\tR\n" +
	"playerName\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\"K\n" +
	"\x0fJoinGameRequest\x12\x1f\n" +
	"\vplayer_name\x18\x01 \x01(\tR\n" +
	"playerName\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\"\xc2\x01\n" +
	"\x10JoinGameResponse\x124\n" +
	"\aplayers\x18\x01 \x03(\v2\x1a.api.proto.snake.v1.PlayerR\aplayers\x12-\n" +
	"\x04food\x18\x02 \x03(\v2\x19.api.proto.snake.v1.PointR\x04food\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x120\n" +
	"\x04mode\x18\x04 \x01(\x0e2\x1c.api.proto.snake.v1.GameModeR\x04mode\"\x8d\x01\n" +
	"\x14SendDirectionRequest\x12\x1f\n" +
	"\vplayer_name\x18\x01 \x01(\tR\n" +
	"playerName\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12;\n" +
	"\tdirection\x18\x03 \x01(\x0e2\x1d.api.proto.snake.v1.DirectionR\tdirection\"\x17\n" +
	"\x15SendDirectionResponse\"\x16\n" +
	"\x14GetTopPlayersRequest\"\xae\x01\n" +
	"\x06Player\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12-\n" +
	"\x04body\x18\x02 \x03(\v2\x19.api.proto.snake.v1.PointR\x04body\x12\x14\n" +
	"\x05alive\x18\x03 \x01(\bR\x05alive\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\x05R\x02id\x12;\n" +
	"\tdirection\x18\x05 \x01(\x0e2\x1d.api.proto.snake.v1.DirectionR\tdirection\"#\n" +
	"\x05Point\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y*K\n" +
	"\bGameMode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tMODE_SOLO\x10\x01\x12\f\n" +
	"\bMODE_1V1\x10\x02\x12\f\n" +
	"\bMODE_FFA\x10\x03*u\n" +
	"\tDirection\x12\x19\n" +
	"\x15DIRECTION_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fDIRECTION_UP\x10\x01\x12\x12\n" +
	"\x0eDIRECTION_DOWN\x10\x02\x12\x12\n" +
	"\x0eDIRECTION_LEFT\x10\x03\x12\x13\n" +
	"\x0fDIRECTION_RIGHT\x10\x042\x94\x03\n" +
	"\x10SnakeGameService\x12[\n" +
	"\n" +
	"CreateRoom\x12%.api.proto.snake.v1.CreateRoomRequest\x1a&.api.proto.snake.v1.CreateRoomResponse\x12W\n" +
	"\bJoinGame\x12#.api.proto.snake.v1.JoinGameRequest\x1a$.api.proto.snake.v1.JoinGameResponse0\x01\x12d\n" +
	"\rSendDirection\x12(.api.proto.snake.v1.SendDirectionRequest\x1a).api.proto.snake.v1.SendDirectionResponse\x12d\n" +
	"\rGetTopPlayers\x12(.api.proto.snake.v1.GetTopPlayersRequest\x1a).api.proto.snake.v1.GetTopPlayersResponseB&Z$GoSnakeGame/api/proto/snake/v1;snakeb\x06proto3"

var (
	file_api_proto_snake_v1_snake_proto_rawDescOnce sync.Once
	file_api_proto_snake_v1_snake_proto_rawDescData []byte
)

func file_api_proto_snake_v1_snake_proto_rawDescGZIP() []byte {
	file_api_proto_snake_v1_snake_proto_rawDescOnce.Do(func() {
		file_api_proto_snake_v1_snake_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_snake_v1_snake_proto_rawDesc), len(file_api_proto_snake_v1_snake_proto_rawDesc)))
	})
	return file_api_proto_snake_v1_snake_proto_rawDescData
}

var file_api_proto_snake_v1_snake_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_snake_v1_snake_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_proto_snake_v1_snake_proto_goTypes = []any{
	(GameMode)(0),                 // 0: api.proto.snake.v1.GameMode
	(Direction)(0),                // 1: api.proto.snake.v1.Direction
	(*ClientMessage)(nil),         // 2: api.proto.snake.v1.ClientMessage
	(*ServerMessage)(nil),         // 3: api.proto.snake.v1.ServerMessage
	(*CreateRoomRequest)(nil),     // 4: api.proto.snake.v1.CreateRoomRequest
	(*CreateRoomResponse)(nil),    // 5: api.proto.snake.v1.CreateRoomResponse
	(*GetTopPlayersResponse)(nil), // 6: api.proto.snake.v1.GetTopPlayersResponse
	(*PlayerScore)(nil),           // 7: api.proto.snake.v1.PlayerScore
	(*JoinGameRequest)(nil),       // 8: api.proto.snake.v1.JoinGameRequest
	(*JoinGameResponse)(nil),      // 9: api.proto.snake.v1.JoinGameResponse
	(*SendDirectionRequest)(nil),  // 10: api.proto.snake.v1.SendDirectionRequest
	(*SendDirectionResponse)(nil), // 11: api.proto.snake.v1.SendDirectionResponse
	(*GetTopPlayersRequest)(nil),  // 12: api.proto.snake.v1.GetTopPlayersRequest
	(*Player)(nil),                // 13: api.proto.snake.v1.Player
	(*Point)(nil),                 // 14: api.proto.snake.v1.Point
}
var file_api_proto_snake_v1_snake_proto_depIdxs = []int32{
	8,  // 0: api.proto.snake.v1.ClientMessage.join:type_name -> api.proto.snake.v1.JoinGameRequest
	10, // 1: api.proto.snake.v1.ClientMessage.direction:type_name -> api.proto.snake.v1.SendDirectionRequest
	12, // 2: api.proto.snake.v1.ClientMessage.top:type_name -> api.proto.snake.v1.GetTopPlayersRequest
	4,  // 3: api.proto.snake.v1.ClientMessage.create_room:type_name -> api.proto.snake.v1.CreateRoomRequest
	9,  // 4: api.proto.snake.v1.ServerMessage.update:type_name -> api.proto.snake.v1.JoinGameResponse
	6,  // 5: api.proto.snake.v1.ServerMessage.top:type_name -> api.proto.snake.v1.GetTopPlayersResponse
	5,  // 6: api.proto.snake.v1.ServerMessage.room_created:type_name -> api.proto.snake.v1.CreateRoomResponse
	0,  // 7: api.proto.snake.v1.CreateRoomRequest.mode:type_name -> api.proto.snake.v1.GameMode
	7,  // 8: api.proto.snake.v1.GetTopPlayersResponse.top_players:type_name -> api.proto.snake.v1.PlayerScore
	13, // 9: api.proto.snake.v1.JoinGameResponse.players:type_name -> api.proto.snake.v1.Player
	14, // 10: api.proto.snake.v1.JoinGameResponse.food:type_name -> api.proto.snake.v1.Point
	0,  // 11: api.proto.snake.v1.JoinGameResponse.mode:type_name -> api.proto.snake.v1.GameMode
	1,  // 12: api.proto.snake.v1.SendDirectionRequest.direction:type_name -> api.proto.snake.v1.Direction
	14, // 13: api.proto.snake.v1.Player.body:type_name -> api.proto.snake.v1.Point
	1,  // 14: api.proto.snake.v1.Player.direction:type_name -> api.proto.snake.v1.Direction
	4,  // 15: api.proto.snake.v1.SnakeGameService.CreateRoom:input_type -> api.proto.snake.v1.CreateRoomRequest
	8,  // 16: api.proto.snake.v1.SnakeGameService.JoinGame:input_type -> api.proto.snake.v1.JoinGameRequest
	10, // 17: api.proto.snake.v1.SnakeGameService.SendDirection:input_type -> api.proto.snake.v1.SendDirectionRequest
	12, // 18: api.proto.snake.v1.SnakeGameService.GetTopPlayers:input_type -> api.proto.snake.v1.GetTopPlayersRequest
	5,  // 19: api.proto.snake.v1.SnakeGameService.CreateRoom:output_type -> api.proto.snake.v1.CreateRoomResponse
	9,  // 20: api.proto.snake.v1.SnakeGameService.JoinGame:output_type -> api.proto.snake.v1.JoinGameResponse
	11, // 21: api.proto.snake.v1.SnakeGameService.SendDirection:output_type -> api.proto.snake.v1.SendDirectionResponse
	6,  // 22: api.proto.snake.v1.SnakeGameService.GetTopPlayers:output_type -> api.proto.snake.v1.GetTopPlayersResponse
	19, // [19:23] is the sub-list for method output_type
	15, // [15:19] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_api_proto_snake_v1_snake_proto_init() }
func file_api_proto_snake_v1_snake_proto_init() {
	if File_api_proto_snake_v1_snake_proto != nil {
		return
	}
	file_api_proto_snake_v1_snake_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientMessage_Join)(nil),
		(*ClientMessage_Direction)(nil),
		(*ClientMessage_Top)(nil),
		(*ClientMessage_CreateRoom)(nil),
	}
	file_api_proto_snake_v1_snake_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_Update)(nil),
		(*ServerMessage_Top)(nil),
		(*ServerMessage_RoomCreated)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_snake_v1_snake_proto_rawDesc), len(file_api_proto_snake_v1_snake_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_snake_v1_snake_proto_goTypes,
		DependencyIndexes: file_api_proto_snake_v1_snake_proto_depIdxs,
		EnumInfos:         file_api_proto_snake_v1_snake_proto_enumTypes,
		MessageInfos:      file_api_proto_snake_v1_snake_proto_msgTypes,
	}.Build()
	File_api_proto_snake_v1_snake_proto = out.File
	file_api_proto_snake_v1_snake_proto_goTypes = nil
	file_api_proto_snake_v1_snake_proto_depIdxs = nil
}
